export const CLIENTE_FETCH_STARTED = 'CLIENTE_FETCH_STARTED';
export const CLIENTE_FETCH_COMPLETED = 'CLIENTE_FETCH_COMPLETED';
export const CLIENTE_FETCH_FAILED = 'CLIENTE_FETCH_FAILED';

export const CLIENTE_ADD_STARTED = 'CLIENTE_ADD_STARTED';
export const CLIENTE_ADD_COMPLETED = 'CLIENTE_ADD_COMPLETED';
export const CLIENTE_ADD_FAILED = 'CLIENTE_ADD_FAILED';

export const CLIENTE_UPDATE_STARTED = 'CLIENTE_UPDATE_STARTED';
export const CLIENTE_UPDATE_COMPLETED = 'CLIENTE_UPDATE_COMPLETED';
export const CLIENTE_UPDATE_FAILED = 'CLIENTE_UPDATE_FAILED';