export const COMPRAS_FETCH_STARTED = 'COMPRAS_FETCH_STARTED';
export const COMPRAS_FETCH_COMPLETED = 'COMPRAS_FETCH_COMPLETED';
export const COMPRAS_FETCH_FAILED = 'COMPRAS_FETCH_FAILED';

export const COMPRA_EXPIRE_STARTED = 'COMPRA_EXPIRE_STARTED';
export const COMPRA_EXPIRE_COMPLETED = 'COMPRA_EXPIRE_COMPLETED';
export const COMPRA_EXPIRE_FAILED = 'COMPRA_EXPIRE_FAILED';

export const COMPRA_ADD_COMPLETED = 'COMPRA_ADD_COMPLETED';
export const COMPRA_ADD_STARTED = 'COMPRA_ADD_STARTED';
export const COMPRA_ADD_FAILED = 'COMPRA_ADD_FAILED';

export const COMPRAS_END_STARTED = 'COMPRAS_END_STARTED';
export const COMPRAS_END_COMPLETED = 'COMPRAS_END_COMPLETED';
export const COMPRAS_END_FAILED = 'COMPRAS_END_FAILED';

export const COMPRAS_PUT_STARTED = 'COMPRAS_PUT_STARTED';
export const COMPRAS_PUT_COMPLETED = 'COMPRAS_PUT_COMPLETED';
export const COMPRAS_PUT_FAILED = 'COMPRAS_PUT_FAILED';
