export const EMPLEADO_FETCH_STARTED = 'EMPLEADO_FETCH_STARTED';
export const EMPLEADO_FETCH_COMPLETED = 'EMPLEADO_FETCH_COMPLETED';
export const EMPLEADO_FETCH_FAILED = 'EMPLEADO_FETCH_FAILED';

export const EMPLEADO_ADD_STARTED = 'EMPLEADO_ADD_STARTED';
export const EMPLEADO_ADD_COMPLETED = 'EMPLEADO_ADD_COMPLETED';
export const EMPLEADO_ADD_FAILED = 'EMPLEADO_ADD_FAILED';

export const EMPLEADO_UPDATE_STARTED = 'EMPLEADO_UPDATE_STARTED';
export const EMPLEADO_UPDATE_COMPLETED = 'EMPLEADO_UPDATE_COMPLETED';
export const EMPLEADO_UPDATE_FAILED = 'EMPLEADO_UPDATE_FAILED';