export const FACTURAS_CLIENTE_FETCH_STARTED = 'FACTURAS_CLIENTE_FETCH_STARTED';
export const FACTURAS_CLIENTE_FETCH_COMPLETED = 'FACTURAS_CLIENTE_FETCH_COMPLETED';
export const FACTURAS_CLIENTE_FETCH_FAILED = 'FACTURAS_CLIENTE_FETCH_FAILED';

export const FACTURAS_FETCH_STARTED = 'FACTURAS_FETCH_STARTED';
export const FACTURAS_FETCH_COMPLETED = 'FACTURAS_FETCH_COMPLETED';
export const FACTURAS_FETCH_FAILED = 'FACTURAS_FETCH_FAILED';

export const FACTURA_ADD_STARTED = 'FACTURA_ADD_STARTED';
export const FACTURA_ADD_COMPLETED = 'FACTURA_ADD_COMPLETED';
export const FACTURA_ADD_FAILED = 'FACTURA_ADD_FAILED';