export const LISTAS_FETCH_COMPLETED = 'LISTAS_FETCH_COMPLETED';
export const LISTAS_FETCH_STARTED = 'LISTAS_FETCH_STARTED';
export const LISTAS_FETCH_FAILED = 'LISTAS_FETCH_FAILED';

export const LISTA_ADD_COMPLETED = 'LISTA_ADD_COMPLETED';
export const LISTA_ADD_STARTED = 'LISTA_ADD_STARTED';
export const LISTA_ADD_FAILED = 'LISTA_ADD_FAILED';

export const LISTA_DECREASE_STARTED = 'LISTA_DECREASE_STARTED';
export const LISTA_DECREASE_COMPLETED = 'LISTA_DECREASE_COMPLETED';
export const LISTA_DECREASE_FAILED = 'LISTA_DECREASE_FAILED';

export const LISTA_INCREASE_STARTED = 'LISTA_INCREASE_STARTED';
export const LISTA_INCREASE_COMPLETED = 'LISTA_INCREASE_COMPLETED';
export const LISTA_INCREASE_FAILED = 'LISTA_INCREASE_FAILED';
