export const PEDIDOS_CLIENTE_FETCH_STARTED = 'PEDIDOS_CLIENTE_FETCH_STARTED';
export const PEDIDOS_CLIENTE_FETCH_COMPLETED = 'PEDIDOS_CLIENTE_FETCH_COMPLETED';
export const PEDIDOS_CLIENTE_FETCH_FAILED = 'PEDIDOS_CLIENTE_FETCH_FAILED';

export const PEDIDOS_FETCH_STARTED = 'PEDIDOS_FETCH_STARTED';
export const PEDIDOS_FETCH_COMPLETED = 'PEDIDOS_FETCH_COMPLETED';
export const PEDIDOS_FETCH_FAILED = 'PEDIDOS_FETCH_FAILED';

export const PEDIDO_ADD_COMPLETED = 'PEDIDO_ADD_COMPLETED';
export const PEDIDO_ADD_STARTED = 'PEDIDO_ADD_STARTED';
export const PEDIDO_ADD_FAILED = 'PEDIDO_ADD_FAILED';

export const PEDIDO_TAKE_STARTED = 'PEDIDO_TAKE_STARTED';
export const PEDIDO_TAKE_COMPLETED = 'PEDIDO_TAKE_COMPLETED';
export const PEDIDO_TAKE_FAILED = 'PEDIDO_TAKE_FAILED';

export const PEDIDO_END_STARTED = 'PEDIDO_END_STARTED';
export const PEDIDO_END_COMPLETED = 'PEDIDO_END_COMPLETED';
export const PEDIDO_END_FAILED = 'PEDIDO_END_FAILED';
