export const PRODUCTOS_FETCH_STARTED = 'PRODUCTOS_FETCH_STARTED';
export const PRODUCTOS_FETCH_COMPLETED = 'PRODUCTOS_FETCH_COMPLETED';
export const PRODUCTOS_FETCH_FAILED = 'PRODUCTOS_FETCH_FAILED';

export const PRODUCTO_ADD_STARTED = 'PRODUCTO_ADD_STARTED';
export const PRODUCTO_ADD_COMPLETED = 'PRODUCTO_ADD_COMPLETED';
export const PRODUCTO_ADD_FAILED = 'PRODUCTO_ADD_FAILED';