export const REGISTRO_ADD_COMPLETED = 'REGISTRO_ADD_COMPLETED';
export const REGISTRO_ADD_STARTED = 'REGISTRO_ADD_STARTED';
export const REGISTRO_ADD_FAILED = 'REGISTRO_ADD_FAILED';

export const REGISTROS_FETCH_COMPLETED = 'REGISTROS_FETCH_COMPLETED';
export const REGISTROS_FETCH_STARTED = 'REGISTROS_FETCH_STARTED';
export const REGISTROS_FETCH_FAILED = 'REGISTROS_FETCH_FAILED';
