export const TIENDAS_FETCH_STARTED = 'TIENDAS_FETCH_STARTED';
export const TIENDAS_FETCH_COMPLETED = 'TIENDAS_FETCH_COMPLETED';
export const TIENDAS_FETCH_FAILED = 'TIENDAS_FETCH_FAILED';

export const TIENDA_ADD_STARTED = 'TIENDA_ADD_STARTED';
export const TIENDA_ADD_COMPLETED = 'TIENDA_ADD_COMPLETED';
export const TIENDA_ADD_FAILED = 'TIENDA_ADD_FAILED';

export const TIENDA_UPDATE_STARTED = 'TIENDA_UPDATE_STARTED';
export const TIENDA_UPDATE_COMPLETED = 'TIENDA_UPDATE_COMPLETED';
export const TIENDA_UPDATE_FAILED = 'TIENDA_UPDATE_FAILED';