export const PUNTUACION_FETCH_STARTED = 'PUNTUACION_FETCH_STARTED';
export const PUNTUACION_FETCH_COMPLETED = 'PUNTUACION_FETCH_COMPLETED';
export const PUNTUACION_FETCH_FAILED = 'PUNTUACION_FETCH_FAILED';

export const COMENTARIOS_FETCH_STARTED = 'COMENTARIOS_FETCH_STARTED';
export const COMENTARIOS_FETCH_COMPLETED = 'COMENTARIOS_FETCH_COMPLETED';
export const COMENTARIOS_FETCH_FAILED = 'COMENTARIOS_FETCH_FAILED';

export const VALORACION_ADD_STARTED = 'VALORACION_ADD_STARTED';
export const VALORACION_ADD_COMPLETED = 'VALORACION_ADD_COMPLETED';
export const VALORACION_ADD_FAILED = 'VALORACION_ADD_FAILED';
